### ISSUE TITLE
Not finding source (index.html)

### ISSUE THREAD

**Issue by yalzeee** [paulsutherland/Polyonic#29] opened 2019-02-10 21:37 UTC
I had an already set project which I've been trying to build for sometime now but for reasons I can't understand isn't working,  so I tried to clone this report and copy my src folder Into it. The electron window opens but can't seem to find my source file(index.html) and in my chrome Dev tool it is showing another index.html file which is blank. I don't know where the problem is coming from.

**Comment by paulsutherland** [comment] 2019-02-11 09:22
@yalzeee 
Ok - what version of Ionic are you using in your existing project?

**Comment by yalzeee** [comment] 2019-02-11 09:42
Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\ZEOY\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 15 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 8.1`

My ionic cli is upgraded but when i started the project i used 3.9.2`

**Comment by paulsutherland** [comment] 2019-02-11 09:52
@yalzeee 
Ok, in a fresh repo, replace the src contents with your existing project's src contents then try:

`npm run build`

then

`npm run dev`

**Comment by paulsutherland** [comment] 2019-02-15 10:18
@yalzeee 
Hi, I would like to close this issue.  Did you resolve the issue you were having?

**Comment by yalzeee** [comment] 2019-02-15 10:27
@paulsutherland
I still haven't been able to resolve the issue
I restarted the whole project and tried copying my src folder followed by trying to add my dependencies to my package.json then installed all of them using npm. I ended up having circular dependencies and I still can't figure out what's wrong. I'm trying to use only the electron part of it though. I have a separate code base for mobile but I wouldn't want to re-write the whole code for desktop and hoped I could use this to do that easily. Would still appreciate any fixes

**Comment by paulsutherland** [comment] 2019-02-15 10:44
@yalzeee
It should be a straight drop in without any modification to your existing code.

Are you able to share a temp repo and I'll help you work through it?

**Comment by yalzeee** [comment] 2019-02-15 12:24
Yes I would and would really appreciate that, here is a repo with the code https://github.com/yalzeee/Temp-Repo

**Comment by paulsutherland** [comment] 2019-02-15 13:11
@yalzeee 
So the problem is the app is not compiling. The Typescript compiler has a number of warnings in the terminal. I would check the entire contents of your src directory copied across ok.

Firstly, if you look at the terminal output it can't find some firebase modules. so:

`npm i firebase -S`

fixes that.

If you are using VSCode - install the TSLInt plugin and you will see the errors that are preventing the app from compiling.

If you look in the app.module.ts file you find that it is trying to pull in the following::

**Pages:**
products
discover

**Components:**
components

**Providers:**
buinesstips
transactions
auth-service
settings
payment

Finally, it can't find the firebaseconfig object for initialising the angular fire module.

Once these things are in place, you should find it compiles and loads properly.

I hope that helps.

**Comment by yalzeee** [comment] 2019-02-15 13:32
@paulsutherland 
Thanks and yeah i didnt add all the pages in the src folder since it is commercial code, hence the errors. I would try this again with that plugin and see if it works out. Thanks again for the help. I could contact you again by email if i have any other problem and if you wouldn't mind, so that you can close this issue.

**Comment by paulsutherland** [comment] 2019-02-15 13:34
@yalzeee 
Yeah - totally understand I thought that would be the case.

That would be great.  You can get me on my mailing list email address:

newsonthegrapevine @ gmail.com

Thanks,

Paul

**Closed by paulsutherland** 2019-02-15 13:34 UTC
